defaults:
  - ../segmentation/ade20k.yaml

experiment:
  name: overfit-ade20k-segmentation-8

data:
  image_size: [256, 256]
  num_workers: 0
  horizontal_flip_probability: 0.0
  query_sampling: fixed
  fixed_query_class_id: 0

training:
  max_steps: 200
  max_samples: 8
  batch_size: 1
  mixed_precision: fp16
  gradient_accumulation_steps: 1
  checkpoint_every: 50
  log_every: 1
  lr_scheduler:
    name: constant
    warmup_steps: 0
